config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :office_locations
  resources :physicians
  resources :patients
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/office_location.rb
class OfficeLocation < ApplicationRecord
  belongs_to :physician
end

app/controllers/office_locations_controller.rb
class OfficeLocationsController < ApplicationController
  before_action :set_office_location, only: [:show, :edit, :update, :destroy]

  # GET /office_locations
  # GET /office_locations.json
  def index
    @office_locations = OfficeLocation.all
  end

  # GET /office_locations/1
  # GET /office_locations/1.json
  def show
  end

  # GET /office_locations/new
  def new
    @office_location = OfficeLocation.new
  end

  # GET /office_locations/1/edit
  def edit
  end

  # POST /office_locations
  # POST /office_locations.json
  def create
    @office_location = OfficeLocation.new(office_location_params)

    respond_to do |format|
      if @office_location.save
        format.html { redirect_to @office_location, notice: 'Office location was successfully created.' }
        format.json { render :show, status: :created, location: @office_location }
      else
        format.html { render :new }
        format.json { render json: @office_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /office_locations/1
  # PATCH/PUT /office_locations/1.json
  def update
    respond_to do |format|
      if @office_location.update(office_location_params)
        format.html { redirect_to @office_location, notice: 'Office location was successfully updated.' }
        format.json { render :show, status: :ok, location: @office_location }
      else
        format.html { render :edit }
        format.json { render json: @office_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /office_locations/1
  # DELETE /office_locations/1.json
  def destroy
    @office_location.destroy
    respond_to do |format|
      format.html { redirect_to office_locations_url, notice: 'Office location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_office_location
      @office_location = OfficeLocation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def office_location_params
      params.require(:office_location).permit(:street_address, :zip, :phone, :physician_id)
    end
end

app/helpers/office_locations_helper.rb
module OfficeLocationsHelper
end

app/views/office_locations/_form.html.erb
<%= form_with(model: office_location, local: true) do |form| %>
  <% if office_location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(office_location.errors.count, "error") %> prohibited this office_location from being saved:</h2>

      <ul>
        <% office_location.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :street_address %>
    <%= form.text_field :street_address %>
  </div>

  <div class="field">
    <%= form.label :zip %>
    <%= form.number_field :zip %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.number_field :phone %>
  </div>

  <div class="field">
    <%= form.label :physician_id %>
    <%= form.text_field :physician_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/office_locations/edit.html.erb
<h1>Editing Office Location</h1>

<%= render 'form', office_location: @office_location %>

<%= link_to 'Show', @office_location %> |
<%= link_to 'Back', office_locations_path %>

app/views/office_locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Office Locations</h1>

<table>
  <thead>
    <tr>
      <th>Street address</th>
      <th>Zip</th>
      <th>Phone</th>
      <th>Physician</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @office_locations.each do |office_location| %>
      <tr>
        <td><%= office_location.street_address %></td>
        <td><%= office_location.zip %></td>
        <td><%= office_location.phone %></td>
        <td><%= office_location.physician_id %></td>
        <td><%= link_to 'Show', office_location %></td>
        <td><%= link_to 'Edit', edit_office_location_path(office_location) %></td>
        <td><%= link_to 'Destroy', office_location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Office Location', new_office_location_path %>

app/views/office_locations/new.html.erb
<h1>New Office Location</h1>

<%= render 'form', office_location: @office_location %>

<%= link_to 'Back', office_locations_path %>

app/views/office_locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Street address:</strong>
  <%= @office_location.street_address %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @office_location.zip %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @office_location.phone %>
</p>

<p>
  <strong>Physician:</strong>
  <%= @office_location.physician_id %>
</p>

<%= link_to 'Edit', edit_office_location_path(@office_location) %> |
<%= link_to 'Back', office_locations_path %>